# Generated by Django 3.2.3 on 2021-06-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210528_2331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
