# Generated by Django 3.2.3 on 2021-06-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
