# Generated by Django 3.2.3 on 2021-06-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_likers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likers',
            field=models.JSONField(default=list, verbose_name='likers'),
        ),
    ]
