# Generated by Django 3.2.3 on 2021-06-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_remove_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likers',
            field=models.JSONField(default=list, verbose_name='likers'),
        ),
    ]
